dataındex = {
  0: 	"Frame Rate",
  1: 	"Times",
  2: 	"Sim stats",
  3: 	"Speeds",
  4: 	"Mach,VVI,g-load",
  5: 	"Weather",
  6: 	"Aircraft atmosphere",
  7: 	"System pressures",
  8: 	"Joystick aileron/elevator/rudder",
  9: 	"Other flight controls",
  10: 	"Artificial Stability aileron/elevator/rudder",
  11: 	"Flight controls aileron/elevator/rudder",
  12: 	"Wing sweep & thrust vectoring",
  13:   "Trim,flap,stats, & speedbreaks",
  14:   "Gear & brakes",
  15:   "Gear & brakes",
  16:   "Gear & brakes",
  17:   "Gear & brakes",
  18:   "Gear & brakes",
  19:   "Gear & brakes",
  20:   "Gear & brakes",
  21:   "Gear & brakes",
  22:   "Gear & brakes",
  23:   "Gear & brakes",
  24:   "Gear & brakes",
  25:   "Gear & brakes",
  26:   "Gear & brakes",
  27:   "Gear & brakes",
  28:   "Gear & brakes",
  29:   "Gear & brakes",
  30:   "Gear & brakes",
  31:   "Gear & brakes",
  32:   "Gear & brakes",
  33:   "Gear & brakes",
  34:   "Gear & brakes",
  35:   "Gear & brakes",
  36:   "Gear & brakes",
  37:   "Gear & brakes",
  38:   "Gear & brakes",
  39:   "Gear & brakes",
  40:   "Gear & brakes",
  41:   "Gear & brakes",
  42:   "Gear & brakes",
  43:   "Gear & brakes",
  44:   "Gear & brakes",
  45:   "Gear & brakes",
  46:   "Gear & brakes",
  47:   "Gear & brakes",
  48:   "Gear & brakes",
  49:   "Gear & brakes",
  50:   "Gear & brakes",
  51:   "Gear & brakes",
  52:   "Gear & brakes",
  53:   "Gear & brakes",
  54:   "Gear & brakes",
  55:   "Gear & brakes",
  56:   "Gear & brakes",
  57:   "Gear & brakes",
  58:   "Gear & brakes",
  59:   "Gear & brakes",
  60:   "Gear & brakes",
  61:   "Gear & brakes",
  62:   "Gear & brakes",
  63:   "Gear & brakes",
  64:   "Gear & brakes",
  65:   "Gear & brakes",
  66:   "Gear & brakes",
  67:   "Gear & brakes",
  68:   "Gear & brakes",
  69:   "Gear & brakes",
  70:   "Gear & brakes",
  71:   "Gear & brakes",
  72:   "Gear & brakes",
  73:   "Gear & brakes",
  74:   "Gear & brakes",
  75:   "Gear & brakes",
  76:   "Gear & brakes",
  77:   "Gear & brakes",
  78:   "Gear & brakes",
  79:   "Gear & brakes",
  80:   "Gear & brakes",
  81:   "Gear & brakes",
  82:   "Gear & brakes",
  83:   "Gear & brakes",
  84:   "Gear & brakes",
  85:   "Gear & brakes",
  86:   "Gear & brakes",
  87:   "Gear & brakes",
  88:   "Gear & brakes",
  89:   "Gear & brakes",
  90:   "Gear & brakes",
  91:   "Gear & brakes",
  92:   "Gear & brakes",
  93:   "Gear & brakes",
  94:   "Gear & brakes",
  95:   "Gear & brakes",
  96:   "Gear & brakes",
  97:   "Gear & brakes",
  98:   "Gear & brakes",
  99:   "Gear & brakes",
  100:   "Gear & brakes",
  101:   "Gear & brakes",
  102:   "Gear & brakes",
  103:   "Gear & brakes",
  104:   "Gear & brakes",
  105:   "Gear & brakes",
  106:   "Gear & brakes",
  107:   "Gear & brakes",
  108:   "Gear & brakes",
  109:   "Gear & brakes",
  110:   "Gear & brakes",
  111:   "Gear & brakes",
  112:   "Gear & brakes",
  113:   "Gear & brakes",
  114:   "Gear & brakes",
  115:   "Gear & brakes",
  116:   "Gear & brakes",
  117:   "Gear & brakes",
  118:   "Gear & brakes",
  119:   "Gear & brakes",
  120:   "Gear & brakes",
  121:   "Gear & brakes",
  122:   "Gear & brakes",
  123:   "Gear & brakes",
  124:   "Gear & brakes",
  125:   "Gear & brakes",
  126:   "Gear & brakes",
  127:   "Gear & brakes",
  128:   "Gear & brakes",
  129:   "Gear & brakes",
  130:   "Gear & brakes",
  131:   "Gear & brakes",
  132:   "Gear & brakes",
  133:   "Gear & brakes",
  134:   "Gear & brakes",
  135:   "Gear & brakes",
  136:   "Gear & brakes"

}
#    Author: Erencan Tayanc
#    Date:24/09/2022

